### ISSUE TITLE
idea: replace dialog menu with something else?

### ISSUE THREAD

**Issue by gotbletu** [zakariaGatter/brash#3]
is a good CLI tool but once the dialog popup to restore a file it turns into a weird TUI with messy colors.

maybe just do similar to `trash-restore` with a list

or use `fzf` instead, you can have multiple hotkeys with fzf
e.g
tab = select single, escape = cancel
`ls  | fzf -m --bind ctrl-a:select-all,ctrl-d:deselect-all,ctrl-t:toggle-all `

**Comment by zakariaGatter** [comment]
Thank you for ur suggestion but I think fzf in over used in almost all cli application

**Comment by gotbletu** [comment]
a simple list would not require dialog or fzf would be best.

but no probs, i guess ill just change the dialog color scheme to match my terminal

**Comment by zakariaGatter** [comment]
I almost seen all ur videos on YouTube and I'm a old subscriber to you YouTube 
I'm away from my computer this days but when I return I'll think about it and we will disgust it

**Comment by gotbletu** [comment]
oh cool, thanks for watching =)
